### ISSUE TITLE
How to fetch all the users contacts

### ISSUE THREAD

**Issue by fardeem** [a-isaiahharvey/rust-macios#122]
Hello! Thank you so much for this package and I apologize in advance for this silly question but I'm struggling quite a bit since I don't really have a background with native objective C. 

How would I go about getting all the users contacts using this package?

**Comment by a-isaiahharvey** [comment]
Good day, I'm sorry for the late response and thank you for using my library 😊. I did some investigation into your question and I updated my library with an example showing how to fetch contacts with the the `CNContactStore ` struct.

```rust
use rust_macios::{
    contacts::{
        CNContactFetchRequest, CNContactFormatter, CNContactFormatterStyle, CNContactStore,
        CNEntityType, ICNContactStore,
    },
    foundation::{INSEnumerator, NSError},
    nsarray,
    objective_c_runtime::traits::PNSObject,
};

fn main() -> Result<(), NSError> {
    // Create a new `CNContactStore` to fetch the contacts from the user's
    // contact database.
    let store = CNContactStore::m_new();

    // Creates a clone of the `CNContactStore` so we can use it after we
    // request access to the user's contact database
    let captured_store = store.clone();

    // Requests access to the users contact database
    store.request_access_for_entity_type_completion_handler(
        CNEntityType::Contacts,
        move |granted: bool, error: NSError| {
            if granted {
                // Create an `NSArray` filled keys you'd like to fetch and use
                // in your program
                //
                // see more: <https://developer.apple.com/documentation/contacts/contact_keys?language=objc>
                let keys_to_fetch =
                    nsarray![CNContactFormatter::descriptor_for_required_keys_for_style(
                        CNContactFormatterStyle::FullName
                    )];

                // Creates the fetch request we would be using to partial
                // fetch data from the database
                let request =
                    CNContactFetchRequest::m_alloc().init_with_keys_to_fetch(keys_to_fetch);

                // We use this method becasue it's easiar to get an enumerator with it
                let fetch_result = captured_store
                    .m_enumerator_for_contact_fetch_request(request)
                    .unwrap();

                for contact in &fetch_result.value().m_all_objects() {
                    println!("{} {}", contact.given_name(), contact.family_name())
                }
            } else {
                panic!("{}", error)
            }
        },
    );

    Ok(())
}
```

and here's a link to the file https://github.com/a-isaiahharvey/rust-macios/blob/7778ba147816e1b0d4d57b12e2daa7cd4a07edcc/examples/contacts/fetch_contacts.rs

**Comment by a-isaiahharvey** [comment]
It's worth noting that when I tried running this example with Visual Studio Code it did not request to access the user's contacts. But it did however work when debugging the executable in Xcode and running example from the Apple's Terminal app and the Warp terminal app.

**Comment by fardeem** [comment]
Thanks for the response! That totally worked. I'm pretty sure VS Code doesn't have access to your contacts hence the issue but it worked for my case. 

Another quick question: how do I fetch the users phone number? How do I include `CNContactPhoneNumbersKey` to `keys_to_fetch` array?

**Comment by a-isaiahharvey** [comment]
so first you import: 

```rust 
use rust_macios::contacts::CNContactPhoneNumbersKey;
```

then you add it to the `nsarray` macro wrapping it in an unsafe because it's an external static and then use the `m_self` method to return the `id` which is the pointer of the descriptor:

```rust
let keys_to_fetch = nsarray![
                    CNContactFormatter::descriptor_for_required_keys_for_style(
                        CNContactFormatterStyle::FullName
                    ),
                    unsafe { CNContactPhoneNumbersKey.m_self() }
                ];
```

And finally to get the user's phone numbers from the we can iterate over the `phone_numbers` method, get the value of the `CNLabledValue` using the `value` method and then return the string containing the phone number using the `string_value` method:

```rust
for contact in &fetch_result.value().m_all_objects() {
    println!("{} {}", contact.given_name(), contact.family_name());

    for number in &contact.phone_numbers() {
        println!("{}", number.value().string_value())
    }
}
```

**Comment by fardeem** [comment]
Amazing it worked thank you so much! Should I make a PR to add this to the example? I think the unsafe bit isn't obvious

**Comment by fardeem** [comment]
Sorry for asking questions here but just running into some really obscure issues:

```
fn request_contact_permission() -> bool {
    let store = CNContactStore::m_new();

    let gr = false;
    store.request_access_for_entity_type_completion_handler(
        CNEntityType::Contacts,
        |granted: bool, _error: NSError| {
            gr = &granted;
        },
    );

    gr
}
```

I want to wait for the `request_access_for_entity_type_completion_handler` to complete and return a final boolean. Is there not a way to await the function so I can return the value of granted from the outer function?

**Comment by a-isaiahharvey** [comment]
> Amazing it worked thank you so much! Should I make a PR to add this to the example? I think the unsafe bit isn't obvious

Sure 😊

> Sorry for asking questions here but just running into some really obscure issues:

It's fine. I love questions because it allows me to be able to test the library against the situations that are asked and allows me to learn more myself on how Rust works

> I want to wait for the request_access_for_entity_type_completion_handler to complete and return a final boolean. Is there 
> not a way to await the function so I can return the value of granted from the outer function?

So because the closure that is passed to `request_access_for_entity_type_completion_handler` function requires to be a lifetime of `'static` you would need to make the closure a move closure by adding the `move` keyword before the closure parameters. Now if we do this the ownership of the `gr` variable would be moved to the closure which if you'd like to use the variable outside the scope of the closure you will not be able to.

To be able to keep our `gr` variable outside of our closure but still be able fetch whether or not we have access to the user's contacts we must wrap our value in RefCell and Arc like this `Arc::new(RefCell::new(false))` and then created a second variable called `captured_gr` and clone `gr`. This variable represents the `gr` variable that's captured by the closure. From within the closure you use the `borrow_mut` method in `captured_gr` to return a mutable reference to `gr`. All you have to do from there is dereference `captured_gr` and assigned granted to it.

Everything would look something similar to this:

```rust
fn request_contact_permission() -> bool {
    let store = CNContactStore::m_new();

    let gr = Arc::new(RefCell::new(false));
    let captured_gr = gr.clone();

    store.request_access_for_entity_type_completion_handler(
        CNEntityType::Contacts,
        move |granted: bool, _error: NSError| {
            let mut captured_gr = captured_gr.borrow_mut();
            *captured_gr = granted;
        },
    );

    let result = gr.borrow();
    *result
}
```

I hope this helps.

P.S. I'm bad at English and kind of new to Rust programming. So I'm sorry if my explanation was terrible.

**Comment by fardeem** [comment]
No, not at all this explanation was brilliant. Thank you again for explaining it so well!
In my adventures with this library I am running into another issue. I'm trying to use this library in conjuction with [tauri](www.tauri.dev) to make a macos native app. I'm running into an issue that I outline here: https://github.com/tauri-apps/tauri/issues/5852

Does any obvious answers come to mind? Could I potentially hire you to help me figure out this problem? If so could we chat over email munirfardeem [at] gmail.com. Thank you again for this library!

**Comment by a-isaiahharvey** [comment]
> No, not at all this explanation was brilliant. Thank you again for explaining it so well!

Thank you so much 😊

> Could I potentially hire you to help me figure out this problem? 

There's no need to hire me. I started to investigate your problem the minute I got some free time and I found a solution.

> Does any obvious answers come to mind?

At first I was thinking that maybe it had something to do with the bundling process so I created a Tauri app with that uses the npm package manager (sorry I don't have yarn), created a button and tried to request access to the user contacts. It did give an error when I debugged the *.app with Xcode. Then I thought maybe I should debug the Unix executable itself and to my surprise it works. So I was right about it being the bundling process but I don't know how I'd go about fixing that.

So my solution is to edit the Info.plist, add the key "Privacy - Contacts Usage Description" with a string value of the description. And it works!

It should look something like this

<img width="912" alt="Screenshot 2022-12-18 at 14 42 14" src="https://user-images.githubusercontent.com/41553768/208314460-afbc6e6b-092b-4acd-ae4e-780a89ea67c7.png">
<img width="805" alt="Screenshot 2022-12-18 at 14 42 40" src="https://user-images.githubusercontent.com/41553768/208314464-ac81bb37-b36f-4198-9267-6ce0245e13b7.png">

**Comment by fardeem** [comment]
This is amazing! Wow! How did you edit the plist file? Was it by opening the file in the bundled .app?

**Comment by a-isaiahharvey** [comment]
Yes I located the *.app in Finder, right click and pressed "Show Package Contents", located the Info.plist in there and open it with Xcode

**Comment by fardeem** [comment]
Sweet I figured it out and the app now works flawlessly! Thank you so much! If you're ever in Chicago please let me know so I can at least treat you to dinner for all the help you provided ❤️

**Comment by a-isaiahharvey** [comment]
I'd love to go there one day to take lots of pictures of nature 😊

**Comment by fardeem** [comment]
Hey! Ran into another and reporting in case you would know. If you run the sample app you made and click on "Don't allow" in the permissions dialog, then the app crashes. Any reason for this? It prints the following before crashing:

```
Error requesting contact permission: Error Domain=CNErrorDomain Code=100 "Access Denied" UserInfo={NSLocalizedDescription=Access Denied, NSLocalizedFailureReason=This application has not been granted permission to access Contacts.}
```

By crashing I mean the app just exits which doesn't seem right to me.

Happy holidays btw!

**Comment by a-isaiahharvey** [comment]
Would you like to try updating to the latest release of the library (v0.4.2) and check out if that fixes the crashing problem?

**Comment by fardeem** [comment]
It works! The only issue is if I try dereferencing it as follows and try to print out the error, it crashes then.

```rust
println!("error: {}", unsafe {
    &error
        .as_ref()
        .map(|error| error.localized_description().to_string())
        .unwrap_or_else(|| "None".to_string())
});
```

**Comment by a-isaiahharvey** [comment]
So I tried multiple combinations of different arguments while I had free time to try to make a more permanent solution but I failed to do so. But I am going to continue to try to find a more permanent solution this is a temporary fix which is using `NSString` with the  `msg_send` macro from the `objc` crate like this

```rust
println!("{:?}", unsafe {
       NSString::from_id(msg_send![error, description])
})
```

**Comment by martial-plains** [comment]
So I was investigating a crate called `icrate`. It seems to be doing a lot of what my crate does but better. I think you should switch to using that crate for your project and I will help you with anything you with any questions you may have on using the crate. For now to be able to use what we talked about in this thread I will show you what changes to make and what to do to the `Cargo.toml`

```toml
[dependencies]
icrate = { git = "https://github.com/madsmtm/objc2", features = [
    "Foundation",
    "Contacts",
    "Contacts_CNContactStore",
] }
block2 = { git = "https://github.com/madsmtm/objc2" }
```

and in the `main.rs` for you src-tauri

```rust
use block2::{Block, ConcreteBlock};
use icrate::{Contacts::{CNContactStore, CNEntityTypeContacts}, objc2::{msg_send_id, class, rc::{Id, Owned}, runtime::Bool}, Foundation::NSError};

#[tauri::command]
fn request_contact_permission() -> bool {
    unsafe {
        let store: Id<CNContactStore, Owned> = msg_send_id![class!(CNContactStore), new];

        let gr = Arc::new(RefCell::new(false));
        let mut captured_gr = gr.clone();

        let block = ConcreteBlock::new(move |granted: Bool, error: *mut NSError| {
            let mut borrowed = captured_gr.borrow_mut();
            *borrowed = granted.as_bool();
        });
        let block = block.copy();
        let block: &Block<(Bool, *mut NSError), ()> = &block;

        store.requestAccessForEntityType_completionHandler(CNEntityTypeContacts, block);

        let result = gr.borrow();
        *result
    }
}
```
